### ISSUE TITLE
Wrong type in the published getting-started document 

### ISSUE THREAD

**Issue by appfrosch** [danielsaidi/DeckKit#4]
I just started to try and implemented this library–thanks for all your efforts and the great documentation first of all!

Found a little bug in the doc thoguht: the published [getting started document](https://danielsaidi.github.io/DeckKit/documentation/deckkit/getting-started/) is using a `CardItem` type that is not available.
![Safari-Getting Started  Documentation-20230205-095428](https://user-images.githubusercontent.com/91844195/216810186-dd5966fd-f701-4acb-86b3-0ce4fb1173d5.png)
When I do look into the source of this documentation though this typo seems to have been fixed–is it possible that the documentation needs to be republished?

**Comment by danielsaidi** [comment]
Thanks for finding this @appfrosch - it’s probably just a publishing issue. I’ll look into it 👍

**Comment by danielsaidi** [comment]
I've pushed a new documentation so it should be live in a few minutes. Thanks again!
